### PR TITLE
KG-487 Add handler for GooglePart.InlineData

### LINKED ISSUE #954: GoogleLLMClient does not support InlineData part type
Got an error on call `gemini-2.5-flash-image` model:

```
java.lang.IllegalStateException: Not supported part type: InlineData(inlineData=ai.koog.prompt.executor.clients.google.GoogleData$Blob@61dde151, thought=null)

	at ai.koog.prompt.executor.clients.google.GoogleLLMClient.processGoogleCandidate(GoogleLLMClient.kt:569)
	at ai.koog.prompt.executor.clients.google.GoogleLLMClient.processGoogleResponse(GoogleLLMClient.kt:614)
	at ai.koog.prompt.executor.clients.google.GoogleLLMClient.execute$suspendImpl(GoogleLLMClient.kt:145)
	at ai.koog.prompt.executor.clients.google.GoogleLLMClient$execute$1.invokeSuspend(GoogleLLMClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
```

`GoogleLLMClient.processGoogleCandidate` should create Message.Assistant with attachments on InlineData part

### PR DESCRIPTION
**Pull request by mltheuser**
YouTrack link: https://youtrack.jetbrains.com/issue/KG-487/GoogleLLMClient-does-not-support-InlineData-part-type
#954

## Motivation and Context

Currently, `GoogleLLMClient` throws an `IllegalStateException: Not supported part type: InlineData` when processing responses from Gemini models that return binary content, such as images (e.g., from `gemini-2.5-flash-image`). This crash occurs because the `processGoogleCandidate` function lacks a handler for the `GooglePart.InlineData` type.

This PR adds the necessary logic to correctly parse `InlineData` parts into `Message.Assistant` messages containing either `ContentPart.Image` or `ContentPart.File`, allowing the client to support multimodal responses from Google's API.

## >> Important Note <<
`gemini-2.5-flash-image` is not in GoogleModels.kt and therefor nor officially supported yet. For that reason there are only unit tests for the `InlineData` handler in this PR. I would be open to add this Model but best to open a separate Issue for it and discuss.

## Breaking Changes
None. This change is a non-breaking bug fix that adds support for a previously unhandled response type. Existing functionality is unaffected.

---

#### Type of the changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [ ] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [x] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [x] An issue describing the proposed change exists
- [x] The pull request includes a link to the issue
- [x] The change was discussed and approved in the issue
- [ ] Docs have been added / updated

### CODE REVIEW

**Review by EugeneTheDev — APPROVED** [review]
Looks good to me, thank you

**Comment by mltheuser** [comment]
Sorry forgot about the linter. Should pass now.

**Comment by mltheuser** [comment]
You might want to remove this from the CONTRIBUTING.md or clarify it further:
```
* Use imports with '*'.
```
It is why I made them * imports in the first place causing the linter error.

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleLLMClient.kt [hunk 1]
```diff
@@ -646,6 +646,28 @@ public open class GoogleLLMClient(
                         )
                     )
 
+                    is GooglePart.InlineData -> {
+                        val inlineData = part.inlineData
+                        val contentPart = when (val mimeType = inlineData.mimeType) {
+                            "image/png", "image/jpeg", "image/webp" -> ContentPart.Image(
+                                content = AttachmentContent.Binary.Bytes(inlineData.data),
+                                format = mimeType.substringAfter("image/"),
+                            )
```
Comment (kpavlov) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleLLMClient.kt:656]: Let's keep `mimeType` as it is to avoid "magical" transformations 

```kotlin
@Serializable
    public data class Image(
        override val content: AttachmentContent,
        override val format: String,
        override val mimeType: String = "image/$format", // 🦄 TooManyMagic
        override val fileName: String? = null,
    ) : Attachment {
````
 
```suggestion
                            "image/png", "image/jpeg", "image/webp" -> ContentPart.Image(
                                content = AttachmentContent.Binary.Bytes(inlineData.data),
                                format = mimeType.substringAfter("image/"),
                                mimeType = mimeType,
                            )
```

**Review by kpavlov — COMMENTED** [review]
Good in general, but I suggest avoiding mimeType conversions and keep it straightforward
