### PR TITLE
fix(embeddings): process Ollama batch embeddings

### LINKED ISSUE #1874: Calculation of embeddins with Ollama doesn't work
I've tried using the method "embed" for Ollama and it doesn't work. The result is:

> Caused by: kotlinx.serialization.MissingFieldException: Field 'embeddings' is required for type with serial name 'ai.koog.prompt.executor.ollama.client.dto.EmbeddingResponseDTO', but it was missing at path: $

The JSON answer from Ollama is: 

> {"embedding":[]}

The cause seems to be that OllamaClient is using the old call "/api/embeddings".
I've tried the current call "/api/embed" and it correctly returns an embeddings array. 
It still doesn't work because it's a 2-dimensional array:

> {"model":"jina/jina-embeddings-v2-base-es","embeddings":[[0.0131005775,...,-0.019281294],"index":0}],"model":"jina/jina-embeddings-v2-base-es","usage":{"prompt_tokens":12,"total_tokens":12}}

t is necessary to reduce it to a 1-dimensional array:

> public class OllamaClient @JvmOverloads constructor(
> ...
> override suspend fun embed(text: String, model: LLModel): List<Double> {
> ...
> return embeddingResponse.embeddings.firstOrNull() ?: emptyList()
> }
> ...
> }

In my case, it works with these 2 changes (URL and 'return') with Ollama 0.21.0 (linux)

### PR DESCRIPTION
**Pull request by aozherelyeva**
Fix Ollama embeddings compatibility with both current and legacy API response formats.

closes #1874

### CODE REVIEW

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt [hunk 1]
```diff
@@ -122,9 +122,12 @@ internal data class EmbeddingBatchRequestDTO(
  */
 @Serializable
 internal data class EmbeddingBatchResponseDTO(
-    @SerialName("embeddings") val embeddings: List<List<Double>>,
+    @SerialName("embeddings") val embeddings: List<List<Double>>? = null,
+    @SerialName("embedding") val embedding: List<Double>? = null,
     @SerialName("model") val modelId: String? = null
-)
+) {
+    fun normalizedEmbeddings(): List<List<Double>> = embeddings ?: embedding?.let(::listOf) ?: emptyList()
```
Comment (Amaneusz) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt:136]: nth: Consider adding some small kdocs explaining why we need to normalize embeddings

**Review by Amaneusz — APPROVED** [review]
Good fix, thank you! 👏 
I left one minor comment :)

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt (hunk 1 above)
Comment (zarechneva-a) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt:136]: Good point, thanks
