### PR TITLE
Add dynamic model discovery and fix tool call IDs for Ollama client

### LINKED ISSUE #140: Trouble running with ollama
This is my code
```
fun main() = runBlocking {
    val agent = simpleSingleRunAgent(
        executor = simpleOllamaAIExecutor(),
        llmModel = LLModel(
            provider = LLMProvider.Meta,
            id = "llama3.2",// llama3.2:1b 
            capabilities = listOf(
                LLMCapability.Tools,
                LLMCapability.Completion
            )
        ),
        systemPrompt = """
        You are a smart pan. You can cook food, boil water, and do other cooking tasks.
        You can also answer questions about cooking and food. You are very smart and can learn new things quickly.
        You are very helpful and will do your best to help me with my cooking tasks.
    """,
        installFeatures = {
            install(Tracing) {
                println("Tracing ==> ${this.messageProcessor}")
            }
        }
    )
    val result = agent.runAndGetResult("Hello! How can you help me?")
    println(result)

}
```

When trying to run this code, I am getting the following exception 

```
Exception in thread "main" java.lang.IllegalStateException: Unknown profile ID llama3.2
	at ai.koog.prompt.executor.ollama.client.dto.OllamaConvertersKt.toOllamaModelId(OllamaConverters.kt:19)
	at ai.koog.prompt.executor.ollama.client.OllamaClient.execute(OllamaClient.kt:67)
	at ai.koog.prompt.executor.llms.SingleLLMPromptExecutor.execute$suspendImpl(SingleLLMPromptExecutor.kt:33)
	at ai.koog.prompt.executor.llms.SingleLLMPromptExecutor.execute(SingleLLMPromptExecutor.kt)
	at ai.koog.agents.core.feature.PromptExecutorProxy.execute(PromptExecutorProxy.kt:43)
	at ai.koog.agents.core.agent.session.AIAgentLLMSession.executeMultiple(AIAgentLLMSession.kt:111)
	at ai.koog.agents.core.agent.session.AIAgentLLMSession.executeSingle(AIAgentLLMSession.kt:115)
	at ai.koog.agents.core.agent.session.AIAgentLLMSession.requestLLM$suspendImpl(AIAgentLLMSession.kt:153)
	at ai.koog.agents.core.agent.session.AIAgentLLMSession.requestLLM(AIAgentLLMSession.kt)
	at ai.koog.agents.core.agent.session.AIAgentLLMWriteSession.requestLLM(AIAgentLLMWriteSession.kt:390)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1$1.invokeSuspend(AIAgentNodes.kt:114)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1$1.invoke(AIAgentNodes.kt)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1$1.invoke(AIAgentNodes.kt)
	at ai.koog.agents.core.agent.context.AIAgentLLMContext$writeSession$2.invokeSuspend(AIAgentLLMContext.kt:47)
	at ai.koog.agents.core.agent.context.AIAgentLLMContext$writeSession$2.invoke(AIAgentLLMContext.kt)
	at ai.koog.agents.core.agent.context.AIAgentLLMContext$writeSession$2.invoke(AIAgentLLMContext.kt)
	at ai.koog.agents.core.utils.RWLock.withWriteLock(RWLock.kt:36)
	at ai.koog.agents.core.agent.context.AIAgentLLMContext.writeSession(AIAgentLLMContext.kt:43)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1.invokeSuspend(AIAgentNodes.kt:109)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1.invoke(AIAgentNodes.kt)
	at ai.koog.agents.core.dsl.extension.AIAgentNodesKt$nodeLLMRequest$1.invoke(AIAgentNodes.kt)
	at ai.koog.agents.core.agent.entity.AIAgentNode.execute(AIAgentNode.kt:122)
	at ai.koog.agents.core.agent.entity.AIAgentNodeBase.executeUnsafe(AIAgentNode.kt:101)
	at ai.koog.agents.core.agent.entity.AIAgentSubgraph.doExecute(AIAgentSubgraph.kt:78)
	at ai.koog.agents.core.agent.entity.AIAgentSubgraph.execute$suspendImpl(AIAgentSubgraph.kt:48)
	at ai.koog.agents.core.agent.entity.AIAgentSubgraph.execute(AIAgentSubgraph.kt)
	at ai.koog.agents.core.agent.entity.AIAgentStrategy.execute(AIAgentStrategy.kt:28)
	at ai.koog.agents.core.agent.AIAgent.run$suspendImpl(AIAgent.kt:147)
	at ai.koog.agents.core.agent.AIAgent$run$1.invokeSuspend(AIAgent.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:70)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at solutions.dreamforge.smartpan.MainKt.main(Main.kt:14)
	at solutions.dreamforge.smartpan.MainKt.main(Main.kt)
```

I do have   ollama running and working tested with ktor in another project

Image

### PR DESCRIPTION
**Pull request by Kashif-E**
This pull request introduces significant enhancements to the `OllamaClient` and its associated components, enabling dynamic model management and improving the flexibility of interacting with the Ollama API. The most notable changes include adding support for dynamic model resolution, introducing a new `OllamaModelFactory` for creating models, and implementing a `OllamaModelManager` for managing model discovery and capabilities. These changes collectively enhance the modularity and extensibility of the Ollama client.

### Enhancements to `OllamaClient`:
* Added support for dynamic model resolution via the `enableDynamicModels` property, allowing models to be resolved dynamically using the `OllamaModelResolver`. This impacts methods like `execute`, `stream`, and `embed`, which now use dynamically resolved model names.
* Introduced new methods such as `getAvailableModels`, `resolveModel`, `createDynamicModel`, `pullModel`, and `suggestSimilarModels`, providing extended functionality for model management.
* Fixed tool call ID generation to use deterministic IDs instead of hardcoded "id" values.

### Introduction of `OllamaModelFactory`:
* Added a new `OllamaModelFactory` class to create and manage Ollama models dynamically. This includes methods for creating models from names, listing available models, grouping models by family, and finding models by patterns.

### Introduction of `OllamaModelManager`:
* Implemented the `OllamaModelManager` class to handle model discovery, caching, and capability detection. It includes features like retrieving available models, resolving models, pulling models from the registry, and invalidating the model cache.

#### Basic Agent with Dynamic Model Selection
```kotlin
fun main() = runBlocking {
    val client = OllamaClient()
    val model = client.modelFromName("llama3.2:3b") // Works with any available model
    
    val agent = simpleSingleRunAgent(
        executor = simpleOllamaAIExecutor(),
        llmModel = model,
        systemPrompt = "You are a helpful assistant."
    )
    
    val result = agent.runAndGetResult("What is Kotlin?")
    println(result)
}
```

#### Model Discovery and Management
```kotlin
suspend fun exploreAvailableModels() {
    val client = OllamaClient()
    
    // List all available models
    val models = client.getAvailableModels()
    println("Available models: ${models.map { it.name }}")
    
    // Group models by family
    val groupedModels = client.listModelsGrouped()
    groupedModels.forEach { (family, modelList) ->
        println("$family: ${modelList.joinToString(", ")}")
    }
    
    // Get best model variant for system constraints
    val bestModel = client.getBestModelVariant("llama3.2", availableMemoryGB = 8)
    println("Best model for 8GB RAM: ${bestModel?.id}")
}
```

#### Automatic Model Creation with Fallbacks
```kotlin
suspend fun createModelWithFallback(preferredModel: String): LLModel {
    val client = OllamaClient()
    
    return try {
        client.modelFromName(preferredModel)
    } catch (e: Exception) {
        val suggestions = client.suggestSimilarModels(preferredModel, limit = 3)
        println("Model '$preferredModel' not available. Similar: ${suggestions.joinToString(", ")}")
        client.modelFromName(suggestions.firstOrNull() ?: "llama3.2")
    }
}
```

#### Temperature Control with Dynamic Models
```kotlin
suspend fun executeWithTemperature() {
    val client = OllamaClient()
    val model = client.modelFromName("qwen2.5-coder:7b")
    
    val agent = simpleSingleRunAgent(
        executor = simpleOllamaAIExecutor(),
        llmModel = model,
        systemPrompt = "You are a coding assistant."
    )
    
    val prompt = prompt {
        user("Write a Kotlin function to reverse a string")
        temperature = 0.3 // Low temperature for precise code generation
    }
    
    val result = agent.runAndGetResult(prompt)
    println(result)
}
```

These changes lay the groundwork for a more robust and flexible integration with the Ollama API, enabling dynamic and efficient model management without maintaining hardcoded model lists.

fixes #140

---
#### Type of the change
- [x] New feature
- [x] Bug fix
- [] Documentation fix

#### Checklist for all pull requests
- [x] The pull request has a description of the proposed change
- [x] I read the [[Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md)](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [x] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [x] An issue describing the proposed change exists
- [x] The pull request includes a link to the issue
- [] The change was discussed and approved in the issue
- [] Docs have been added/updated

### CODE REVIEW

**Review by Rizzen — APPROVED** [review]
Hello @Kashif-E! Thank you for your contribution!

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelManager.kt [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+     */
+    public suspend fun resolveModel(modelName: String): LLModel? {
+        val availableModels = getAvailableModels()
+        val matchedModel = findModelByName(availableModels, modelName)
+            ?: return null
+
+        val capabilities = detectCapabilities(matchedModel)
+        
+        return LLModel(
+            provider = LLMProvider.Meta, // Default to Meta for now
```
Comment (ptitjes) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelManager.kt:94]: You should create a `LLMProvider.Ollama` provider.

The LLMProvider seems to represent who provides the model, not who did the model. For example, `OpenRouter` is an LLMProvider, though it provides models made by Meta, Microsoft, etc.

Also, we need to change the LLModels defined in `OllamaModels` to use that new provider.

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelManager.kt [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+            id = "ollama-${matchedModel.name}",
```
Comment (ptitjes) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelManager.kt:95]: I propose that we simply remove the `"ollama-"` and `"dynamic-"` prefixes you introduced. We should use the exact name advertised by Ollama as the model id.

Also, we have to change the ids of the hard-coded models in `OllamaModels`.

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaConverters.kt [hunk 3]
```diff
@@ -11,12 +11,32 @@ import kotlinx.serialization.json.Json
...
+                }
+            }
+
+            else -> {
+                // Log warning and use ID directly as fallback
+                println("Warning: Unknown model ID ${this.id}, using ID directly. Consider using OllamaModelResolver for dynamic model support.")
+                this.id
+            }
+        }
+    }
```
Comment (ptitjes) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaConverters.kt:39]: If we remove the `"ollama-"` and `"dynamic-"` prefixes and use the real Ollama model name as id, all this should be removed.

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt [hunk 4]
```diff
@@ -25,21 +25,23 @@ import kotlinx.coroutines.flow.flow
...
  * @property baseClient The HTTP client used for making requests.
+ * @property timeoutConfig Timeout configuration for HTTP requests.
+ * @property enableDynamicModels Whether to enable dynamic model resolution.
  */
 public class OllamaClient(
     private val baseUrl: String = "http://localhost:11434",
     baseClient: HttpClient = HttpClient(engineFactoryProvider()),
-    timeoutConfig: ConnectionTimeoutConfig = ConnectionTimeoutConfig()
+    timeoutConfig: ConnectionTimeoutConfig = ConnectionTimeoutConfig(),
+    private val enableDynamicModels: Boolean = true
```
Comment (ptitjes) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt:39]: I propose that we remove that and use the model names advertised by Ollama directly without any `"ollama-"` or `"dynamic-"` prefixes.

**Review by ptitjes — COMMENTED** [review]
That's far better than what I did in my PR.

In my opinion, we have to use the real model name advertised by Ollama, without any prefix added.

**Comment by ptitjes** [comment]
@Rizzen wow, you merged really fast. Can I do a PR with the changes that I propose above?

**Comment by Rizzen** [comment]
@ptitjes Yeah, I merged it pretty fast because we're working on actual ollama integration tests right now, and these changes are very useful. I suggest to wait for PR with these tests and then make PR with your proposals. What do you think about it?

**Comment by Kashif-E** [comment]
Thanks @Rizzen  for the merge, `koog` is definitely kool 😉
@ptitjes really excited about your upcoming changes, they are going to simplify things a lot

**Comment by Kashif-E** [comment]
resoling conversations for now

**Comment by ptitjes** [comment]
@Rizzen sorry, I made the PR anyway. It doesn't change the API introduced by @Kashif-E, it just simplify things.
https://github.com/JetBrains/koog/pull/149
