### PR TITLE
fix: make system fingerprint nullable

### LINKED ISSUE #1000: Dashscope deserialization issue
the error:
```log
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1094: Unexpected 'null' value instead of string literal at path: $.systemFingerprint
                                                                                                    JSON input: .....0847,"system_fingerprint":null,"model":"qwen-flash","id":"ch.....
```

request:
```shell
curl 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions' \
  -X 'POST' \
  -H 'Accept: application/json' \
  -H 'Accept-Charset: UTF-8' \
  -H 'Authorization: Bearer sk-xxxxxxxxxxxx' \
  -H 'Content-Length: 1348' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: ktor-client' \
  --data-raw '{"messages":[{"role":"system","content":"You are an AI assistant."},{"role":"user","content":"hello"}],"model":"qwen-flash","stream":false}' \
  --compressed
```

According to [the document](https://www.alibabacloud.com/help/en/model-studio/use-qwen-by-calling-api#a25484c79d1ca:~:text=system_fingerprint%20string-,This%20parameter%20is%20currently%20fixed%20to%20null.,-usage%20object), the `system_fingerprint` is fixed to `null` now.

cc @Stream29 could you help to take a look?

### PR DESCRIPTION
**Pull request by Stream29**
## Motivation and Context

Fix #1000 .

## Breaking Changes

`systemFingerprint` property for `DashScope` becomes nullable.

---

#### Type of the changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [ ] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [x] All new and existing tests passed

### CODE REVIEW

**Review by kpavlov — COMMENTED** [review]
@Stream29, thank you for the fix!
Would you mind adding/updating a test for your change

**Comment by Stream29** [comment]
@kpavlov OK.

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-dashscope-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/dashscope/models/DashscopeSerializationTest.kt [hunk 1]
```diff
@@ -193,4 +194,171 @@ class DashscopeSerializationTest {
...
+        assertEquals("chatcmpl-123", response.id)
+        assertEquals("qwen-plus", response.model)
+        assertEquals(1677652288L, response.created)
+        assertEquals(null, response.systemFingerprint)
+        assertEquals("chat.completion", response.objectType)
+        assertEquals(1, response.choices.size)
+        assertNotNull(response.usage)
+        assertEquals(10, response.usage?.promptTokens)
+        assertEquals(20, response.usage?.completionTokens)
+        assertEquals(30, response.usage?.totalTokens)
```
Comment (kpavlov) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-dashscope-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/dashscope/models/DashscopeSerializationTest.kt]: nit: it's better to use [kotest json assertions](https://kotest.io/docs/assertions/json/json-overview.html) next time, for readability

**Review by kpavlov — APPROVED** [review]
Thank you, @Stream29

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-dashscope-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/dashscope/models/DashscopeSerializationTest.kt (hunk 1 above)
Comment (Stream29) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-dashscope-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/dashscope/models/DashscopeSerializationTest.kt]: I agree.

**Review by kpavlov — APPROVED** [review]
😻

**Review by EugeneTheDev — APPROVED** [review]

**Review by aozherelyeva — APPROVED** [review]
Thank you for the contribution!
