### PR TITLE
KG-178 Drop coroutine context elements and update OTel feature span management

### LINKED ISSUE #1037: IllegalStateException: Span not found in OpenTelemetry (LangFuse exporter) During Parallel Tool Execution
# Environment:

Koog Version: 0.5.0
Feature: ai.koog.agents.features.opentelemetry.feature.OpenTelemetry (for Langfuse exporting)
Java Agent: opentelemetry-javaagent

# Summary
When running a Koog agent with the OpenTelemetry.Feature enabled, the entire agent run fails with an IllegalStateException only when executing tools in parallel (in my case, specifically running the same tool with different arguments in parallel).

This appears to be a race condition or a coroutine context propagation issue within the OpenTelemetry feature. The trace logs show that the individual tools actually succeed, but the agent crashes immediately after when the OTel listener tries (and fails) to find the completed tool's span.

# Steps to Reproduce
- Create a Koog agent and install the OpenTelemetry.Feature.
- Define an agent strategy (graph) that uses parallel tool execution. In our case, we are using nodeExecuteMultipleTools(parallelTools = true) (or a custom subgraph that contains it).
- Run the agent in a way that triggers this parallel tool call node.
- The agent will execute the tools, but instead of proceeding, it will crash at the multi tool execution stage.

## Expected Behavior
- The parallel tools should execute successfully. The OpenTelemetry.Feature should correctly find and complete the spans for each parallel tool, and the agent run should continue.

## Actual Behavior
- The agent run fails and throws a fatal exception. The logs show the following error:
```
java.lang.IllegalStateException: Span with id: agent.[...].run.[...].node.executeTools.tool.[TOOL_NAME] not found
	at ai.koog.agents.features.opentelemetry.feature.OpenTelemetry$Feature$install$12.invokeSuspend(OpenTelemetry.kt:518)
	at ai.koog.agents.core.feature.AIAgentPipeline$interceptToolCallCompleted$$inlined$createConditionalHandler$1.invokeSuspend(AIAgentPipeline.kt:1214)
	at ai.koog.agents.core.feature.AIAgentPipeline.onToolCallCompleted(AIAgentPipeline.kt:431)
	at ai.koog.agents.core.environment.GenericAgentEnvironment.processToolCall(GenericAgentEnvironment.kt:149)
	at ai.koog.agents.core.environment.GenericAgentEnvironment$processToolCallMultiple$results$1$1$1.invokeSuspend(GenericAgentEnvironment.kt:167)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
    ...
```
Trace analysis confirms that the tool span (e.g., tool.convertToForeignCurrency) completes successfully, but the parent node.executeTools span and the main run span both fail with the Span not found error.

# Suspected Cause 
From asking LLMs, this seems to be a coroutine context propagation issue. The OpenTelemetry feature's listener (likely onToolCallCompleted) is executing in a different coroutine context than the one that started the tool. Because the OTel context isn't correctly propagated by the opentelemetry-javaagent during the parallel kotlinx-coroutines dispatch, the listener fails to find the span, throwing an IllegalStateException and crashing the agent.

This is likely caused by an incompatibility between the opentelemetry-javaagent version and the kotlinx-coroutines version used by the project.

### PR DESCRIPTION
**Pull request by sdubov**
KG-178. Drop coroutine context elements and update OTel feature span management

- AgentExecutionInfo instance provides information about an agent execution, including an execution path. This info can be used as an identifier for spans structure. Used patched version for the execution info that matches spans hierarchy structure and updated the OpenTelemetry feature by using this data to manage spans;
- Add Strategy and Subgraph spans for better representing Koog agent execution in Open Telemetry spans. Split SubgraphExecuteSpan from NodeExecutiuonSpan to track subgraph execution within strategies;
- Replace SpanProcessor with SpanCollector to avoid names clashing. Improved span lifecycle management logic.

## Motivation and Context
Open Telemetry feature uses coroutine context to propagate the information about agent execution context. Use a native `AIAgentContext` for this purpose instead as the coroutine context might be not reliable for critical data.

## Breaking Changes
No

---

#### Type of the changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [x] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [x] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [x] An issue describing the proposed change exists
- [x] The pull request includes a link to the issue
- [x] The change was discussed and approved in the issue
- [x] Docs have been added / updated

### CODE REVIEW

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/StatefulSingleUseAIAgent.kt [hunk 1]
```diff
@@ -87,49 +85,42 @@ public abstract class StatefulSingleUseAIAgent<Input, Output, TContext : AIAgent
...
-                        State.Failed(Exception("result is null"))
-                    }
-                }
+            logger.debug { formatLog(id, runId, "Starting agent execution") }
+            pipeline.onAgentStarting<Input, Output>(agentRunEventId, context.executionInfo, runId, this@StatefulSingleUseAIAgent, context)
+
+            val result = try {
+                @Suppress("UNCHECKED_CAST")
+                strategy.execute(context = context, input = agentInput)
+            } catch (e: Throwable) {
```
Comment (kpavlov) [inline agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/StatefulSingleUseAIAgent.kt]: Let's catch Exception, not Throwable.

**Review by Rizzen — APPROVED** [review]
