### PR TITLE
Fix Bedrock tool schema JSON generation to handle nested objects

### LINKED ISSUE #1259: JsonDecodingException when AnthropicClaude4_5Haiku generates a list of strings instead of objects for TripPlan
When running the `trip-planning-example` agent with the `BedrockModels.AnthropicClaude4_5Haiku` model, a fatal `kotlinx.serialization.json.internal.JsonDecodingException` occurs during the `clarifyUserPlan` subgraph execution.

The agent is expected to generate a structured `TripPlan` object, which contains a `List<TripPlan.Step>`. The `TripPlan.Step` is a data class with multiple fields (`location`, `fromDate`, `toDate`, etc.), as defined in `Structs.kt`.

However, the `AnthropicClaude4_5Haiku` model generates a simple JSON array of strings for the `steps` field instead of an array of `Step` objects. This causes the `kotlinx.serialization` library to fail during deserialization, as it encounters a `JsonLiteral` (a string) where a `JsonObject` is expected.

The error message clearly indicates this mismatch:
`Expected JsonObject, but had JsonLiteral as the serialized body of ai.koog.agents.examples.tripplanning.TripPlan.Step`

This suggests that this specific model struggles with adhering to the complex nested JSON schema required by the `TripPlan` tool, especially when the prompt instructions in the `clarifyUserPlan` subgraph (in `Agent.kt`) are not explicit about the output format.

### Steps to Reproduce

1.  Configure the `trip-planning-example` in `Agent.kt` to use the `BedrockModels.AnthropicClaude4_5Haiku` model.
2.  Run the `Main.kt` file to start the agent.
3.  Start a conversation with the agent to plan a trip. For example:
    *   User: `plan a trip from Sofia to Plovdiv for tomorrow`
4.  Continue the conversation, providing details as requested by the agent (e.g., transport type, interests).
5.  When the agent attempts to finalize the plan in the `clarifyUserPlan` subgraph, it calls the `finalize_task_result` tool with an incorrectly formatted `TripPlan` structure.
6.  The application crashes with a `JsonDecodingException`.

### Environment

*   **Koog Version:** 0.5.4
*   **OS:** Windows 11
*   **LLM Model:** `BedrockModels.AnthropicClaude4_5Haiku` (via `eu-central-1`)
*   **Project:** `koog/examples/trip-planning-example`
*   **Relevant Dependencies:** `kotlinx.serialization`

#### Stack Trace
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Expected JsonObject, but had JsonLiteral as the serialized body of ai.koog.agents.examples.tripplanning.TripPlan.Step at element: $.0 JSON input: "08:00 - Тръгване със автобус от София до Пловдив (около 2 часа пътуване)" at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24) at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32) at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:410) at ai.koog.agents.examples.tripplanning.TripPlan$Step$$serializer.deserialize(Structs.kt:47) ...
Kotlin
#### OpenTelemetry Trace Snippet (`koog.node.input`)

This trace from the `callToolsHacked` node shows the malformed `steps` array generated by the model, which is an array of strings instead of objects.
```json
{
  "langgraph_step": 22,
  "langgraph_node": "callToolsHacked",
  "attributes": {
    "koog.node.input": [
      {
        "id": "toolu_bdrk_01DCxUskM9wX7Yxz3sUjPjRW",
        "tool": "finalize_task_result",
        "parts": [
          {
            "text": {
              "steps": [
                "08:00 - Тръгване със автобус от София до Пловдив (около 2 часа пътуване)",
                "10:30 - Пристигане в Пловдив, преход до Римския театър",
                "10:45 - Посещение на Римския театър - един от най-добре запазените театри от Римската империя",
                "12:00 - Разходка по Стария град (улица \"Йовков\", \"Константина\") с историческите керемидени къщи",
                "13:30 - Обяд в традиционен ресторант със българска кухня",
                "15:00 - Посещение на храм \"Св. Луковиц\" или другите религиозни обекти в старата част",
                "16:00 - Катерене на Мечешки рид за панорамна гледка към целия град",
                "17:00 - Разходка по Мечешкия рид и фотосесия",
                "18:00 - Възвращане към центъра, свободно време за пазаруване или отпочивка",
                "19:30 - Тръгване със автобус обратно към София",
                "21:30 - Пристигане в София"
              ]
            }
          }
        ],
        "metaInfo": {
          "timestamp": "2025-12-10T17:38:27.868473700Z",
          "totalTokensCount": 4612,
          "inputTokensCount": 4243,
          "outputTokensCount": 369
        }
      }
    ],
    "langfuse.observation.metadata.langgraph_step": "22",
    "gen_ai.conversation.id": "e5afadc7-01d0-4743-a771-1ea4fe3bbea5",
    "koog.node.name": "callToolsHacked",
    "langfuse.observation.metadata.langgraph_node": "callToolsHacked"
  },
  "resourceAttributes": {
    "os.arch": "amd64",
    "os.type": "Windows 11",
    "os.version": "10.0",
    "service.instance.time": "2025-12-10T17:35:08.987113800Z",
    "service.name": "ai.koog",
    "service.version": "0.5.4"
  },
  "scope": {
    "name": "ai.koog",
    "version": "0.5.4",
    "attributes": {}
  }
}
```

### PR DESCRIPTION
**Pull request by Sujin1135**
<!--
Thank you for opening a pull request!

Please add a brief description of the proposed change here.
Also, please tick the appropriate points in the checklist below.
-->

  ## Motivation and Context                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  Fixes #1259                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  When using Bedrock models with tools that have complex nested types (e.g., `List<Object>`), the JSON schema generation incorrectly serialized all non-primitive list item types as `"string"`. This caused LLMs to generate string arrays instead of properly structured object arrays, leading to deserialization failures.                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  **Example issue:**                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  - Tool parameter: `steps: List<TripPlan.Step>` where `Step` is an object with properties                                                                                                                                                                                                                                                                                                                                                                                         
  - Previous schema: `{"type": "array", "items": {"type": "string"}}`                                                                                                                                                                                                                                                                                                                                                                                                              
  - LLM output: `["Sofia to Plovdiv", "Visit museums"]` ❌ (strings instead of objects)                                                                                                                                                                                                                                                                                                                                                                                            
  - Expected output: `[{"location": "Sofia", "fromDate": "2026-01-13", ...}, ...]` ✅                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  ## Breaking Changes                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  None. This is an internal fix to JSON schema generation logic that makes it work correctly according to JSON Schema specification. No public API changes.                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  #### Type of the changes                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  - [ ] New feature (non-breaking change which adds functionality)                                                                                                                                                                                                                                                                                                                                                                                                                 
  - [x] Bug fix (non-breaking change which fixes an issue)                                                                                                                                                                                                                                                                                                                                                                                                                         
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)                                                                                                                                                                                                                                                                                                                                                                                         
  - [ ] Documentation update                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  - [ ] Tests improvement                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  - [ ] Refactoring                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  - [ ] CI/CD changes                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  - [ ] Dependencies update                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  #### Checklist                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  - [x] The pull request has a description of the proposed change                                                                                                                                                                                                                                                                                                                                                                                                                  
  - [x] I read the [Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request                                                                                                                                                                                                                                                                                                                                          
  - [x] The pull request uses **`develop`** as the base branch                                                                                                                                                                                                                                                                                                                                                                                                                     
  - [x] Tests for the changes have been added (existing tests pass)                                                                                                                                                                                                                                                                                                                                                                                                                
  - [x] All new and existing tests passed                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  ##### Additional steps for pull requests adding a new feature                                                                                                                                                                                                                                                                                                                                                                                                                    
  - [x] An issue describing the proposed change exists (#1259)                                                                                                                                                                                                                                                                                                                                                                                                                     
  - [x] The pull request includes a link to the issue                                                                                                                                                                                                                                                                                                                                                                                                                              
  - [x] The change was discussed and approved in the issue                                                                                                                                                                                                                                                                                                                                                                                                                         
  - [ ] Docs have been added / updated (not needed for internal fix)

### CODE REVIEW

**Comment by westphal-jan** [comment]
Thanks for the fix. I just want to mention that every client kind of implements their own version of ToolDescriptor to Json schema generation which seems extremely unnecessary. For example I temporarily fixed the issue by just re-using the already existing OllamaGenerator as it seemed relatively mature:

```
private object BedrockToolSerialization : ToolDescriptorSchemaGenerator {
    private val generator = OllamaToolDescriptorSchemaGenerator()
    override fun generate(toolDescriptor: ToolDescriptor): JsonObject {
        return generator.generate(toolDescriptor)
    }
}
```

Note, I couldn't re-use the Anthropic client serialization because it doesn't support anyOf for some reason which also again just shows how inconsistent the Json schema generation is.
https://github.com/JetBrains/koog/blob/0.6.0/prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicLLMClient.kt#L572

**Comment by EugeneTheDev** [comment]
Thank you @westphal-jan for pointing these things out. We are aware of JSON schema generation inconsistency and will try to improve it later

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerialization.kt [hunk 1]
```diff
@@ -35,15 +35,19 @@ internal object BedrockToolSerialization {
...
             is ToolParameterType.List -> {
                 put("type", "array")
-                putJsonObject("items") {
-                    when (type.itemsType) {
-                        ToolParameterType.Boolean -> put("type", "boolean")
-                        ToolParameterType.Float -> put("type", "number")
-                        ToolParameterType.Integer -> put("type", "integer")
-                        ToolParameterType.String -> put("type", "string")
-                        else -> put("type", "string")
+                val itemDescriptor = ToolParameterDescriptor(
```
Comment (EugeneTheDev) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerialization.kt]: This `ToolParameterDescriptor` construction with manual `description` filter later doesn't look clean. Let's introduce a helper function for now, like [this one](https://github.com/JetBrains/koog/blob/99575bf9fe61f92d62a85fba155b18fad3a300be/prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicLLMClient.kt#L572), and keep the logic and recursion here?

**Review by EugeneTheDev — CHANGES_REQUESTED** [review]

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerialization.kt (hunk 1 above)
Comment (mango1135) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerialization.kt]: @EugeneTheDev Thanks for the feedback! I've introduced a buildTypeSchema helper function to handle the type serialization cleanly.

**Review by EugeneTheDev — APPROVED** [review]
Thank you, looks good now
