### PR TITLE
fix(agents): Add ids for reasoning messages and improve reasoning process to fix status 400 from openai

### LINKED ISSUE #1712: OpenAI Responses API adapter replays reasoning items incorrectly
In Koog `0.7.1`, `gpt-5-codex` can fail in multi-step tool runs because the OpenAI Responses API adapter replays reasoning items incorrectly on the next turn.

### PR DESCRIPTION
**Pull request by tiginamaria**
Bugs:
* The ID of incoming reasoning messages was ignored, but it's required for outgoing messages. We generated it manually, but it didn't match the format `rs_***`, so we got 400 from OpenAI. The right approach here is to store the original ids of the reasoning messages
* For codex models, the reasoning is hidden, so we received empty text and summary, and while trying to send it back with the response, we also got 400 from OpenAI. The right fix here is to ignore empty reasoning, as it's hidden and makes no sense for the user.

Fixes:
* Add ids to reasoning messages
* Fix the reasoning messages response content, the text was ignored
* Ignore empty reasoning messages
* Add reasoning capability to control which models support reasoning
* Increase tokens limit in tests for reasoning as in case of end of tokens, no end of conversation is received and the test fails

closes #1712
and bug reported in Slack https://kotlinlang.slack.com/archives/C08SLB97W23/p1773062179788829

### CODE REVIEW

File: prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrameFlowBuilder.kt [hunk 1]
```diff
@@ -256,6 +263,7 @@ public class StreamFrameFlowBuilder(
         val index: Int?,
     ) {
         fun appendArgumentsDelta(argumentsDelta: String?): PendingToolCall {
+            require(this.index == index)
```
Comment (devcrocod) [inline prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrameFlowBuilder.kt:266]: I don't understand what is being validated here or where the second index is coming from

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt [hunk 2]
```diff
@@ -342,44 +344,65 @@ public open class OpenAILLMClient @JvmOverloads constructor(
...
+                                    StreamFrame.TextComplete(item.value, it.outputIndex)
+                                }
+
                                 is Item.Reasoning -> {
-                                    StreamFrame.ReasoningComplete(
-                                        text = item.content?.map { content -> content.text } ?: emptyList(),
-                                        summary = item.summary.map { content -> content.text },
-                                        encrypted = item.encryptedContent,
+                                    // https://developers.openai.com/api/reference/resources/responses/streaming-events#response.reasoning_text.done
+                                    if (item.summary.isEmpty() && item.content?.isEmpty() ?: true) {
```
Comment (devcrocod) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt]: `isNullOrEmpty`

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt [hunk 3]
```diff
@@ -291,6 +292,7 @@ public open class OpenAILLMClient @JvmOverloads constructor(
         return selectExecutionStrategy(prompt, model) { params ->
             when (params) {
                 is OpenAIResponsesParams -> {
+                    model.requireCapability(LLMCapability.OpenAIEndpoint.Responses)
```
Comment (devcrocod) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt:317]: Why isn't capability checked for the Chat Completions API?

**Review by devcrocod — APPROVED** [review]
LGTM 👍

File: prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrameFlowBuilder.kt (hunk 1 above)
Comment (tiginamaria) [reply prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrameFlowBuilder.kt:266]: All parts have indexes, and this check verifies that we don't append a delta from one part to another (or we don't skip the end of the part event)

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt (hunk 3 above)
Comment (tiginamaria) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt:317]: Added a check. Thank you for noticing

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt (hunk 2 above)
Comment (tiginamaria) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt]: True
