### PR TITLE
fix(prompt): ensure `reasoningContent` present with tool calls in DeepSeek

### LINKED ISSUE #1599: There is an issue with the support for DeepSeek's deepseek-reasoner model, as it is prone to errors.
errors info: 
`Caused by: ai.koog.http.client.KoogHttpClientException: Error from client: DeepSeekLLMClient
Status code: 400
Error body:
{"error":{"message":"Missing `reasoning_content` field in the assistant message at message index 3. For more information, please refer to https://api-docs.deepseek.com/guides/thinking_mode#tool-calls","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}

	at ai.koog.http.client.ktor.KtorKoogHttpClient.processResponse(KtorKoogHttpClient.kt:79)
	at ai.koog.http.client.ktor.KtorKoogHttpClient.access$processResponse(KtorKoogHttpClient.kt:50)
	at ai.koog.http.client.ktor.KtorKoogHttpClient$post$2.invokeSuspend(KtorKoogHttpClient.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
`

### PR DESCRIPTION
**Pull request by Stream29**
This PR keeps `reasoningContent` in tool calls and merge them with tool calls to satisfy DeepSeek API requirements.

closes #1599

### CODE REVIEW

**Review by devcrocod — COMMENTED** [review]
This PR changes the base class for all OpenAI compatible clients, so I see a risk of regressions for other clients

**Comment by Stream29** [comment]
@devcrocod `OpenAIMessage.toMessageResponses`'s old behavior is to remove the thinking content when a tool call presents. To fix this issue, it has to be changed.

**Comment by devcrocod** [comment]
> OpenAIMessage.toMessageResponses's old behavior is to remove the thinking content when a tool call presents. To fix this issue, it has to be changed

I understand that. However, since this change affects all clients, I’d like to see test coverage for each of them. Unfortunately, "OpenAI-compatible" is not a strict specification, and providers that claim OpenAI compatibility do not always follow it consistently

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client-base/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/base/AbstractOpenAILLMClient.kt [hunk 1]
```diff
@@ -393,71 +393,89 @@ public abstract class AbstractOpenAILLMClient<TResponse : OpenAIBaseLLMResponse,
...
+        finishReason: String?,
+        metaInfo: ResponseMetaInfo
+    ): List<Message.Response> {
+        check(this is OpenAIMessage.Assistant) { "Expected OpenAIMessage.Assistant, got $this" }
+        val messageResponses = sequence {
+            yield(reasoningMessageOrNull(metaInfo))
+            yieldAll(toolCallMessages(metaInfo))
+            yield(assistantMessageOrNull(finishReason, metaInfo))
+            yield(audioMessageOrNull(metaInfo, finishReason))
+        }.filterNotNull().toList()
```
Comment (devcrocod) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client-base/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/base/AbstractOpenAILLMClient.kt:469]: To me, this looks like a slightly odd construct. sequence creates a coroutine and is usually useful when working with a large number of objects. In this case, it seems like unnecessary overhead

**Review by devcrocod — APPROVED** [review]
👍
