### PR TITLE
[prompt] [integration-tests] Fix intput/output token counts for OpenAILLMClient

### LINKED ISSUE #368: inputTokens/outputTokens are null for OpenAIModels.CostOptimized models
Code snippet to reproduce
```kotlin
import ai.koog.agents.example.ApiKeyService
import ai.koog.prompt.dsl.prompt
import ai.koog.prompt.executor.clients.openai.OpenAIModels
import ai.koog.prompt.executor.llms.all.simpleOpenAIExecutor
import kotlinx.coroutines.runBlocking

fun main(): Unit = runBlocking {
    val executor = simpleOpenAIExecutor(ApiKeyService.openAIApiKey)
    val prompt = prompt("example-prompt") {
        system("You are a helpful assistant.")
        user("What is the answer to life, the universe, and everything?")
    }

    val response = executor.execute(prompt, OpenAIModels.CostOptimized.GPT4oMini, emptyList())
    println(response)
}
```

Result:
```
[Assistant(content=The answer to life, the universe, and everything, as famously concluded in Douglas Adams' "The Hitchhiker's Guide to the Galaxy," is the number 42. This has become a pop culture reference for the absurdity of seeking a simple answer to such a complex question. The book humorously suggests that the question itself remains unknown, leaving the significance of the answer ambiguous., metaInfo=ResponseMetaInfo(timestamp=2025-06-30T13:21:33.098097Z, totalTokensCount=107, inputTokensCount=null, outputTokensCount=null), attachment=null, finishReason=stop)]
```

`totalTokensCount` is present, but `inputTokensCount` and `outputTokensCount` are null. These fields should instead contain actual values.

### PR DESCRIPTION
**Pull request by EugeneTheDev**
Fix input/output tokens in `OpenAILLMClient`. Add check for tokens count in integration tests. Also applied credentials resolver plugin in integration tests (just like in examples) to make running the tests and passing API keys a bit easier when developing.

Fixes #368

### CODE REVIEW

**Comment by skarpovdev** [comment]
Do these changes with `credentialResolver` need to be reflected in the TESTING.md file or it's still actual?

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt [hunk 1]
```diff
@@ -328,6 +328,9 @@ public open class OpenAILLMClient(
                 setBody(request)
             }
 
+            val responseJson = response.bodyAsText()
+            println(responseJson)
```
Comment (tiginamaria) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt]: Extra `println`?

**Review by tiginamaria — APPROVED** [review]
Looks good, thank you!

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt (hunk 1 above)
Comment (EugeneTheDev) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt]: Nice catch, sorry, forgot it

**Comment by EugeneTheDev** [comment]
@skarpovdev 
> Do these changes with `credentialResolver` need to be reflected in the TESTING.md file or it's still actual?
This does not affect current approaches, they would still work, but it's still a good idea to mention this option there too, thanks
