### PR TITLE
KG-597: Add error handling for tool argument parsing, result serialization, and subgraph tool execution failures

### LINKED ISSUE #1169: Unhandled exceptions on LLM‑initiated invalid tool/node calls terminate agent run
#### Environment
- Library: `Koog` 0.5.3
- Example project: `trip-planning-example`
- LLM model: `GoogleModels.Gemini2_5Flash` (switched from the default)
- OS/Runtime: JVM (Gradle run), Kotlin Multiplatform project

#### Summary
When the LLM occasionally references a non‑existent tool/node or returns an incompatible tool result, the execution fails with an unhandled exception in `AIAgentNode`, which aborts the entire agent run. The current behavior logs the error and invokes the pipeline’s `onNodeExecutionFailed` hook, but the exception is then rethrown, causing the process to terminate instead of allowing the agent to recover and ask the LLM to select a valid tool/node.

#### Details
- The failure manifests as a `kotlinx.serialization.SerializationException` during tool result handling, and/or when the LLM produces a call to a non‑existent tool/node.
- Excerpt from logs (from `scratch.txt`):
  - `Error executing node (name: callToolsHacked): No tag in stack for requested element`
  - Repeated `kotlinx.serialization.SerializationException: No tag in stack for requested element` originating from `ToolResult` serialization and `GenericAgentEnvironment.processToolCall`
  - The run ends with non‑zero exit (`Execution exception reported by server!` and Gradle task FAILED)
- Relevant code path (current behavior in `AIAgentNode`):
  ```kotlin
  } catch (e: Exception) {
      logger.error(e) { "Error executing node (name: $name): ${e.message}" }
      context.pipeline.onNodeExecutionFailed(this@AIAgentNode, context, input, inputType, e)
      throw e
  }
  ```
  The exception is rethrown after reporting, which prevents the agent from recovering from LLM‑provoked mistakes.

#### Steps to Reproduce
1. In `trip-planning-example`, switch the model to `GoogleModels.Gemini2_5Flash`.
2. Run the example and interact normally (e.g., ask for a plan in Sofia). 
3. Intermittently, the LLM will issue a malformed tool call or reference a tool/node that does not exist.
4. Observe the serialization error and subsequent termination of the run.

#### Actual Behavior
- The agent logs the failure, rethrows the exception from `AIAgentNode`, and terminates the run, returning a non‑zero exit status.

#### Expected/Desired Behavior
- LLM‑provoked execution errors (e.g., non‑existent tool/node names or incompatible tool result shapes) are handled gracefully so the agent can continue.
- Ideally, the error would be surfaced back to the LLM in a structured manner, allowing it to choose a valid tool/node on the next step without aborting the entire run.

#### A gentle suggestion
Would you consider an option to treat such failures as recoverable at the node level (e.g., via a configurable retry/recovery policy or a pipeline strategy), where `onNodeExecutionFailed` could return a structured signal back to the LLM instead of rethrowing immediately? This could enable the agent to request a corrected tool/node call from the model and proceed without terminating the session.

If a configuration already exists to achieve this (e.g., by customizing the pipeline or error policy to suppress the rethrow and respond to the LLM with an error context), guidance on how to enable it in `Koog 0.5.3` would be greatly appreciated.

#### Additional Context
- Example node name in logs: `callToolsHacked` (from the example’s execution path)
- Exceptions originate around `ToolResult` serialization and `GenericAgentEnvironment.processToolCall` when the LLM tool call is malformed.

Thank you in advance for your time and for the excellent work on Koog! If any extra logs or a minimal reproduction are useful, I can provide them.

Image

### PR DESCRIPTION
**Pull request by WorldOfBasti**
## Description
This PR adds robust error handling for tool argument parsing, result serialization, and subgraph tool execution failures. Instead of crashing, the agent should now handle these errors and return failure results.
Issue also described in [KG-597](https://youtrack.jetbrains.com/issue/KG-597) / #1169

### Tool Argument Parsing errors
* Added error handling when parsing tool call JSON arguments fails
* Tool calls with invalid JSON now call the `onToolValidationFailed` callback and return a `ToolResultKind.ValidationError` with an error message instead of crashing

### Tool result serialization errors
* Catch exceptions when calling `decodeResult()`
* Parsing failures now return `Result.Failure` with an error message

### Subgraph finish tool hanlding
* Ensures parsing/execution failures route back to the LLM for correction

#### Type of the changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [ ] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md) before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [x] Tests for the changes have been added
- [x] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [x] An issue describing the proposed change exists
- [x] The pull request includes a link to the issue
- [ ] The change was discussed and approved in the issue
- [ ] Docs have been added / updated

### CODE REVIEW

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/environment/ContextualAgentEnvironment.kt [hunk 1]
```diff
@@ -20,14 +23,44 @@ public class ContextualAgentEnvironment(
...
+                message = "Failed to parse tool arguments: ${e.message}",
+                error = e.toAgentError(),
+                context = context
+            )
+            return ReceivedToolResult(
+                id = toolCall.id,
+                tool = toolCall.tool,
+                toolArgs = JsonObject(emptyMap()),
+                toolDescription = null,
+                content = "Failed to parse tool arguments: ${e.message}",
```
Comment (EugeneTheDev) [inline agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/environment/ContextualAgentEnvironment.kt]: nit: Can be extracted into variable to avoid duplicating

File: prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt [hunk 2]
```diff
@@ -238,12 +239,26 @@ public sealed interface Message {
                 this(id, tool, ContentPart.Text(content), metaInfo)
 
             /**
-             * Lazily parses the content of the tool call as a JSON object.
+             * Lazily parses and caches the result of parsing [content] as a JSON object.
              */
-            val contentJson: JsonObject by lazy {
-                Json.parseToJsonElement(content).jsonObject
+            val contentJsonResult: kotlin.Result<JsonObject> by lazy {
```
Comment (EugeneTheDev) [inline prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt:243]: `Result` that can throw an exception when accessed looks confusing. Can't you simplify it? 

```kotlin
runCatching {
    Json.parseToJsonElement(content).jsonObject
}
```

File: prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrame.kt [hunk 3]
```diff
@@ -37,11 +38,25 @@ public sealed interface StreamFrame {
     ) : StreamFrame {
 
         /**
-         * Lazily parses the content of the tool call as a JSON object.
+         * Lazily parses and caches the result of parsing [content] as a JSON object.
          */
-        val contentJson: JsonObject by lazy {
-            Json.parseToJsonElement(content).jsonObject
+        private val contentJsonResult: Result<JsonObject> by lazy {
```
Comment (EugeneTheDev) [inline prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/streaming/StreamFrame.kt]: The same here about replacing the whole block with a simple `runCatching`. Also, why is it private?

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt [hunk 4]
```diff
@@ -66,7 +67,7 @@ internal object BedrockAmazonNovaSerialization {
                             toolUse = NovaToolUse(
                                 toolUseId = msg.id ?: Uuid.random().toString(),
                                 name = msg.tool,
-                                input = msg.contentJson,
+                                input = msg.contentJsonResult.getOrElse { JsonObject(emptyMap()) },
```
Comment (EugeneTheDev) [inline prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt:70]: Did you update serializers for other model families in Bedrock client, or no updates were needed there?

**Review by EugeneTheDev — CHANGES_REQUESTED** [review]
Thank you, generally looks good, a few comments

File: prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt (hunk 4 above)
Comment (WorldOfBasti) [reply prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt:70]: I updated `BedrockAnthropicClaudeSerialization` as well now. The others don't have tool support as far as I understand.

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt [hunk 5]
```diff
@@ -8,6 +8,7 @@ import ai.koog.agents.core.environment.toSafeResult
 import ai.koog.agents.core.tools.Tool
 import ai.koog.prompt.message.ContentPart
 import ai.koog.prompt.message.Message
+import io.ktor.utils.io.CancellationException
```
Comment (EugeneTheDev) [inline agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt]: nit: wrong `CancellationException`

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/environment/ContextualAgentEnvironment.kt [hunk 6]
```diff
@@ -2,8 +2,11 @@ package ai.koog.agents.core.environment
 
 import ai.koog.agents.core.agent.context.AIAgentContext
 import ai.koog.agents.core.agent.execution.AgentExecutionInfo
+import ai.koog.agents.core.feature.model.toAgentError
 import ai.koog.prompt.message.Message
 import io.github.oshai.kotlinlogging.KotlinLogging
+import io.ktor.utils.io.CancellationException
```
Comment (EugeneTheDev) [inline agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/environment/ContextualAgentEnvironment.kt]: nit: wrong `CancellationException`

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt [hunk 7]
```diff
@@ -27,7 +28,9 @@ import ai.koog.prompt.markdown.markdown
 import ai.koog.prompt.message.Message
 import ai.koog.prompt.params.LLMParams
 import ai.koog.prompt.processor.ResponseProcessor
+import io.ktor.utils.io.CancellationException
```
Comment (EugeneTheDev) [inline agents/agents-core/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt]: nit: wrong `CancellationException`

File: agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/feature/Persistence.kt [hunk 8]
```diff
@@ -20,6 +20,7 @@ import ai.koog.agents.core.utils.SerializationUtils
 import ai.koog.agents.snapshot.providers.PersistenceStorageProvider
 import ai.koog.prompt.message.Message
 import io.github.oshai.kotlinlogging.KotlinLogging
+import io.ktor.utils.io.CancellationException
```
Comment (EugeneTheDev) [inline agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/feature/Persistence.kt]: nit: wrong `CancellationException`

File: agents/agents-mcp-server/src/commonMain/kotlin/ai/koog/agents/mcp/server/McpServer.kt [hunk 9]
```diff
@@ -10,6 +10,7 @@ import io.ktor.server.engine.ApplicationEngineFactory
 import io.ktor.server.engine.EmbeddedServer
 import io.ktor.server.engine.EngineConnectorConfig
 import io.ktor.server.engine.embeddedServer
+import io.ktor.utils.io.CancellationException
```
Comment (EugeneTheDev) [inline agents/agents-mcp-server/src/commonMain/kotlin/ai/koog/agents/mcp/server/McpServer.kt]: nit: wrong `CancellationException`

**Review by EugeneTheDev — CHANGES_REQUESTED** [review]
I've also noticed a number of wrong imports, can you please fix these? Other than that looks good

File: agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt (hunk 5 above)
Comment (WorldOfBasti) [reply agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt]: @EugeneTheDev Good catch, I missed those. Fixed them in the latest commit!

**Review by EugeneTheDev — APPROVED** [review]
